import card.CreditCard;
import card.bonuses.AccumulativeDebitCard;
import card.bonuses.CashbackCreditCard;
import card.bonuses.CashbackDebitCard;
import card.bonuses.CumulativePointsCreditCard;

public class Main {
    public static void main(String[] args) {
        System.out.println("Выпускаем кредитную карту с лимитом 10000");
        CreditCard defaultCreditCard = new CreditCard(10000.);
        defaultCreditCard.getAvailableFundsInfo();
        System.out.println("Пополняем на 5000");
        defaultCreditCard.replenish(5000.);
        defaultCreditCard.getBalanceInfo();
        System.out.println("Оплачиваем на 5000");
        defaultCreditCard.pay(5000.);
        defaultCreditCard.getBalanceInfo();
        System.out.println("Оплачиваем на 3000");
        defaultCreditCard.pay(3000.);
        defaultCreditCard.getBalanceInfo();
        System.out.println("Пополняем на 2000");
        defaultCreditCard.replenish(2000.);
        defaultCreditCard.getBalanceInfo();
        System.out.println("Пополняем на 2000");
        defaultCreditCard.replenish(2000.);
        defaultCreditCard.getBalanceInfo();
        System.out.println();
        System.out.println("Создаем кредитную карту с кэшбэком 5% от покупок в 5000");
        CashbackCreditCard cashbackCreditCard = new CashbackCreditCard(10000., 0.05, 5000.);
        cashbackCreditCard.getAvailableFundsInfo();
        System.out.println("Пополняем на 5000");
        cashbackCreditCard.replenish(5000.);
        cashbackCreditCard.getBalanceInfo();
        System.out.println("Оплачиваем на 5000");
        cashbackCreditCard.pay(5000.);
        cashbackCreditCard.getBalanceInfo();
        System.out.println("Пополняем на 4999");
        cashbackCreditCard.replenish(4999.);
        cashbackCreditCard.getBalanceInfo();
        System.out.println("Оплачиваем на 4999");
        cashbackCreditCard.pay(4999.);
        cashbackCreditCard.getBalanceInfo();
        System.out.println();
        System.out.println("Создаем дебетовую карту с кэшбэком 5% от покупок в 5000");
        CashbackDebitCard cashbackDebitCard = new CashbackDebitCard(0.05, 5000.);
        cashbackDebitCard.getAvailableFundsInfo();
        System.out.println("Пополняем на 5000");
        cashbackDebitCard.replenish(5000.);
        cashbackDebitCard.getBalanceInfo();
        System.out.println("Оплачиваем на 5000");
        cashbackDebitCard.pay(5000.);
        cashbackDebitCard.getBalanceInfo();
        System.out.println("Пополняем на 4999");
        cashbackDebitCard.replenish(4999.);
        cashbackDebitCard.getBalanceInfo();
        System.out.println("Оплачиваем на 4999");
        cashbackDebitCard.pay(4999.);
        cashbackDebitCard.getBalanceInfo();
        System.out.println();
        System.out.println("Создаем кредитную карту с накопительными баллами в 1% от суммы покупок");
        CumulativePointsCreditCard cumulativePointsCreditCard = new CumulativePointsCreditCard(10000., 0.01);
        cumulativePointsCreditCard.getAvailableFundsInfo();
        System.out.println("Пополняем на 7000");
        cumulativePointsCreditCard.replenish(7000.);
        cumulativePointsCreditCard.getBalanceInfo();
        System.out.println("Оплачиваем на 7000");
        cumulativePointsCreditCard.pay(7000.);
        cumulativePointsCreditCard.getAvailableFundsInfo();
        System.out.println("Пополняем на 2500");
        cumulativePointsCreditCard.replenish(2500.);
        cumulativePointsCreditCard.getBalanceInfo();
        System.out.println("Оплачиваем на 2500");
        cumulativePointsCreditCard.pay(2500.);
        cumulativePointsCreditCard.getAvailableFundsInfo();
        System.out.println();
        System.out.println();
        System.out.println("Создаем дебетовую карту с накоплением в 0.005% от суммы пополнения");
        AccumulativeDebitCard accumulativeDebitCard = new AccumulativeDebitCard(0.00005);
        accumulativeDebitCard.getAvailableFundsInfo();
        System.out.println("Пополняем на 100000");
        accumulativeDebitCard.replenish(100000.);
        accumulativeDebitCard.getBalanceInfo();
        System.out.println("Пополняем на 7000");
        accumulativeDebitCard.replenish(7000.);
        accumulativeDebitCard.getBalanceInfo();
        System.out.println("Пополняем на 10000");
        accumulativeDebitCard.replenish(10000.);
        accumulativeDebitCard.getBalanceInfo();
    }
}